"""empty message

Revision ID: 0aa8215abd5e
Revises: 5310019e189b
Create Date: 2022-05-11 04:57:22.710404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa8215abd5e'
down_revision = '5310019e189b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'image_cover')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('image_cover', sa.VARCHAR(length=5000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
