"""empty message

Revision ID: 5f8c28e54423
Revises: 76a0d8d0c460
Create Date: 2022-05-14 01:32:31.821165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8c28e54423'
down_revision = '76a0d8d0c460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('author', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'author')
    # ### end Alembic commands ###
