"""empty message

Revision ID: 6c35b44ad11d
Revises: 4fe462edd7cd
Create Date: 2022-05-11 08:14:32.254632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c35b44ad11d'
down_revision = '4fe462edd7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'path')
    # ### end Alembic commands ###
