"""empty message

Revision ID: 76a0d8d0c460
Revises: f61f697a2330
Create Date: 2022-05-14 01:17:29.498314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a0d8d0c460'
down_revision = 'f61f697a2330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('media', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'media')
    # ### end Alembic commands ###
