"""empty message

Revision ID: ed1cb2fe9ed6
Revises: b65ba4f2ac68
Create Date: 2022-05-12 11:12:55.903788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1cb2fe9ed6'
down_revision = 'b65ba4f2ac68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'header')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('header', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
