"""empty message

Revision ID: f61f697a2330
Revises: ed1cb2fe9ed6
Create Date: 2022-05-13 09:00:14.546506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61f697a2330'
down_revision = 'ed1cb2fe9ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('header', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'header')
    # ### end Alembic commands ###
